// Predefined list of skills - ONLY these skills are allowed
const PREDEFINED_SKILLS = [
	"C programming",
	"C++ programming",
	"Java programming",
	"Python programming",
	"C# programming",
	"Go programming",
	"Rust programming",
	"Object-Oriented Programming (OOP)",
	"Data Structures and Algorithms",
	"Debugging and optimization",
	"HTML",
	"CSS",
	"JavaScript",
	"Bootstrap",
	"Tailwind CSS",
	"React",
	"Angular",
	"Vue.js",
	"Node.js",
	"Express.js",
	"Django",
	"Flask",
	"Spring Boot",
	"RESTful API development",
	"GraphQL API development",
	"Web performance optimization",
	"Progressive Web Apps (PWA)",
	"Android app development",
	"Kotlin development",
	"iOS app development",
	"Swift programming",
	"Flutter development",
	"React Native development",
	"Mobile UI/UX design",
	"Mobile app testing",
	"Mobile app deployment",
	"AWS",
	"Microsoft Azure",
	"Google Cloud Platform",
	"Docker",
	"Kubernetes",
	"CI/CD",
	"Jenkins",
	"GitHub Actions",
	"GitLab CI",
	"Terraform",
	"Ansible",
	"Serverless computing",
	"Monitoring and logging",
	"Prometheus",
	"Grafana",
	"Machine learning",
	"Deep learning",
	"TensorFlow",
	"Keras",
	"PyTorch",
	"Scikit-learn",
	"Data preprocessing",
	"Feature engineering",
	"Natural Language Processing (NLP)",
	"Computer Vision",
	"Model evaluation",
	"AI model optimization",
	"MLOps",
	"Data visualization",
	"Matplotlib",
	"Seaborn",
	"Power BI",
	"Tableau",
	"Data cleaning",
	"Data preprocessing with Pandas",
	"NumPy",
	"Statistical analysis",
	"Hypothesis testing",
	"Big Data",
	"Hadoop",
	"Apache Spark",
	"Business analytics",
	"Network security",
	"Ethical hacking",
	"Penetration testing",
	"Web application security",
	"Secure coding practices",
	"Cryptography",
	"Identity and access management",
	"Security auditing",
	"Software design patterns",
	"MVC architecture",
	"MVVM architecture",
	"Singleton pattern",
	"Factory pattern",
	"Microservices architecture",
	"Event-driven architecture",
	"API gateway design",
	"Load balancing",
	"System design",
	"Distributed systems",
	"Scalability optimization",
	"Performance optimization",
	"Git",
	"GitHub",
	"GitLab",
	"Bitbucket",
	"Unit testing",
	"Integration testing",
	"Automation testing",
	"Selenium",
	"JUnit",
	"PyTest",
	"Agile methodology",
	"Scrum framework",
	"Operating systems",
	"Linux administration",
	"Windows Server management",
	"Shell scripting",
	"Bash scripting",
	"PowerShell scripting",
	"Blockchain development",
	"Solidity programming",
	"Smart contract development",
	"Ethereum development",
	"Internet of Things (IoT)",
	"IoT device programming",
	"WebRTC",
	"Real-time communication systems",
	"AR/VR development",
	"Quantum computing basics",
	"Software project management",
];

// Helper function to validate skill
const isValidSkill = (skillName) => {
	if (!skillName || typeof skillName !== "string") return false;
	const normalizedInput = skillName.trim().toLowerCase();
	return PREDEFINED_SKILLS.some(
		(skill) => skill.toLowerCase() === normalizedInput
	);
};

module.exports = { PREDEFINED_SKILLS, isValidSkill };
